### ISSUE TITLE
API returning 'null' for all values when /jhu-edu/brief/

### ISSUE THREAD

**Issue by lumaaaaaa** [Laeyoung/Wuhan-Coronavirus-API#1]

**Comment by lumaaaaaa** [comment]
Change spreadsheet key to "1wQVypefm946ch4XDp37uZ-wartW4V7ILdg-qYiDXUHM".

**Comment by Laeyoung** [comment]
@lumaaaaaa Thank you for reporting it!

Spreadsheet has been changed at latest release.

**Comment by Laeyoung** [comment]
@lumaaaaaa 

This issue has been fixed at https://github.com/Laeyoung/Wuhan-Coronavirus-API/releases/tag/0.2.0

**Comment by lumaaaaaa** [comment]
Thanks for the quick fix! I made a program utilizing this API so I wouldn't need to parse out of the JHU .json. It works spectacularly. Thanks for your work!
