### ISSUE TITLE
I made a WordPress plugin using your API

### ISSUE THREAD

**Issue by yduke** [Laeyoung/Wuhan-Coronavirus-API#11]
Hi Laeyoung, this is NOT an issue
I am Duke Yin from China,
I made a WordPress plugin with your COVID-19 API (https://github.com/Laeyoung/COVID-19-API),
It called "Corona virus data", shows numbers of Cofirmed, deaths and recovers.

The plugin page:[https://wordpress.org/plugins/corona-virus-data/]( https://wordpress.org/plugins/corona-virus-data/)

Thank you for providing this API, if anything inappropriate with this plugin, please let me know, I will try to fix it.

I tried to send you email, but seems your mail box is full, so I open this  just to let you know. Good job!

**Comment by 112bzo** [comment]
The API server may be down, please check your firewall settings and try again later.

**Comment by Laeyoung** [comment]
@yduke Thank you for using this api : )

Can I add your Wordpress plugin [here](https://github.com/Laeyoung/COVID-19-API#services-using-covid-19-api)

**Comment by yduke** [comment]
@Laeyoung That would be honored : )
Thanks!
