### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by 112bzo** [Laeyoung/Wuhan-Coronavirus-API#12]
Hello,

I have use the WP plugin but i see a error.

`The API server may be down, please check your firewall settings and try again later.
`

**Comment by yduke** [comment]
@112bzo I think you should post this on: https://wordpress.org/support/plugin/corona-virus-data/
I am the author of the WordPress plugin, seeing this error means you can't get the API result on your network environment.
The API is up and running as I tested at my place, try go 
`https://wuhan-coronavirus-api.laeyoung.endpoint.ainize.ai/jhu-edu/brief`
to see if you can get the data or not.

Sorry @Laeyoung

**Comment by 112bzo** [comment]
Thank yduke : you'r page give a DNS_PROBE_FINISHED_NXDOMAIN but oke i look at the wp site.

**Comment by yduke** [comment]
Hi @112bzo 
I've written what I know to your issue in [here](https://wordpress.org/support/topic/api-server-down/)

In short: you've got some DNS problem on resolving api domain name.

Solve this and the API will bring you its data. :)
