### ISSUE TITLE
Requesting “term of use” or “privacy policy” documents.

### ISSUE THREAD

**Issue by yduke** [Laeyoung/Wuhan-Coronavirus-API#13]
Hi @Laeyoung 
Bad news is, the Wordpress plugin team has shut my plugin down, they send me a email I quote:

> A legal issue with the service you're using was brought to our attention.

> https://wordpress.org/plugins/corona-virus-data/

> Your plugin uses https://github.com/Laeyoung/COVID-19-API which has no published information regarding the license and terms of use for the service. It has them for the source code, which is great, but as a service they're obligated to protect you (and your users) with at the very least a terms of use or privacy policy.

> We cannot reopen your plugin with this issue. 

So is there any possible you can include a “term of use” or “privacy policy” in your README?

I promise the plugin will never go commercial and will always be free, I can find the ainiza.ai terms and policy goes here:
https://ainize.ai/terms

And the terms of use of “
Novel Coronavirus (COVID-19) Cases, provided by JHU CSSE” here:

https://github.com/CSSEGISandData/COVID-19/blob/master/README.md

I think you could claim your API respect the MIT license and give users freedom to use in none-commercial use including showing data on their website etc.

Thank you and best regards.

Duke Yin

**Comment by Laeyoung** [comment]
Hi @yduke 

I added license description and term of service at README.md.

I didn't know there was term of service of CSSEGISandData/COVID-19 until you let me know. I think the ToS seem a little bit strict as I assume ☹️.

**Comment by yduke** [comment]
Thank you @Laeyoung 
I've submit your readme url to the wordpress plugin review team, hopefully the plugin will be reopen to public soon. :)

**Comment by Laeyoung** [comment]
@yduke I hope so. If you need any helps, let me know : )

**Comment by aliokfi** [comment]
- - [x] [[[[[[@![image](https://user-images.githubusercontent.com/69582912/131921244-a730241f-64df-4b75-a4af-a179846bd030.jpeg)]()]()]()]()]()]()
