### ISSUE TITLE
empty city

### ISSUE THREAD

**Issue by kravetsone** [Laeyoung/Wuhan-Coronavirus-API#5]
returns an empty city and take the time to add to the country

**Comment by Laeyoung** [comment]
Hello, @kravetsone 

Could you explain it in more detail? or give me some examples?

**Comment by kravetsone** [comment]
I sorted by infestations and from top 2 to top 4 returns empty cities

**Comment by Laeyoung** [comment]
I got it!

This api service refers CSSE data (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-08-2020.csv)

As you see the link, only large countries like China and US have city or states data. And the other countries don't have city data.

**Comment by Aledorka** [comment]
> возвращает пустой город и не торопитесь добавлять в страну

I have the same thing empty data for provinces

**Comment by Laeyoung** [comment]
Hi, @kravetsone and @Aledorka 

I think the new feature could help you to solve this issue. Plz check [new feature](https://github.com/Laeyoung/COVID-19-API#latest)

**Comment by Aledorka** [comment]
разве Россия, не представляет данные по городам?

**Comment by Laeyoung** [comment]
@Aledorka 

Извините, я не смог найти источник данных, который бы предоставлял информацию о русском языке по городам. (translated by Google Translate)

**Comment by Aledorka** [comment]
> @Aledorka
> 
> Извините, я не смог найти источник данных, который бы предоставлял информацию о русском языке по городам. (translated by Google Translate)

https://yandex.ru/web-maps/covid19?ll=41.775580%2C54.894027&z=3
and
https://coronavirus-monitor.ru/
