### ISSUE TITLE
Your dataset are all returning null values now

### ISSUE THREAD

**Issue by andersot72** [Laeyoung/Wuhan-Coronavirus-API#8]
curl -X GET "https://wuhan-coronavirus-api.laeyoung.endpoint.ainize.ai/jhu-edu/brief" -H "accept: application/json" 
{"confirmed":0,"deaths":0,"recovered":0}%

**Comment by Laeyoung** [comment]
Hi, @andersot72 

I think it is a kind of timing issue. This api refer 3 csv files at [CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series). When new date's column has been created, every cells according to the column would be 0.

I will fix it soon, thank you for reporting it 😎!

**Comment by Laeyoung** [comment]
Maybe, this was caused by #9 issue.

**Comment by andersot72** [comment]
thanks much and thanks very much for providing this, I signed up for the Ainize as well :-)

**Comment by Laeyoung** [comment]
@andersot72 Oh thank you!!

Did you get a "Welcome to Ainize beta" mail?
