### ISSUE TITLE
Hi dataset is returning 0 as values

### ISSUE THREAD

**Issue by Chukwudi4** [Laeyoung/Wuhan-Coronavirus-API#9]

**Comment by Laeyoung** [comment]
Hello, @Chukwudi4 

Could you tell me a little more detail?

**Comment by Chukwudi4** [comment]
The values of confirmed, deaths and recovered were 0. The cities returned with the location and the values of confirmed, deaths and recovered for each city were 0.

The issue seems to be resolved as of now.

**Comment by Laeyoung** [comment]
@Chukwudi4

It was happened again for last 4 hours.  And I found the cause of this issue.

This api refer 3 csv files at [CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19). I found that they created a column of new date first, and then filled data in new cells after 4~5 hours.

like this
- https://github.com/CSSEGISandData/COVID-19/blob/94ef22c3cb4cc655806d2d01da084741df672324/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
- https://github.com/CSSEGISandData/COVID-19/blob/94ef22c3cb4cc655806d2d01da084741df672324/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv

It caused this issue, and I will fix ASAP.

Thanks for letting me know this issue.

**Comment by Laeyoung** [comment]
It has been fixed at https://github.com/Laeyoung/COVID-19-API/commit/84e19913411e611c8767f95b882d6a7c5f3a4a73
